Repository heysaiyad/dev-toolkit, pull requests merged in 2025-10, with the labels that each got.

#54 fix: fixed landing page
  index.html
  index.html.backup
  sw.js
Labels: hacktoberfest-accepted

#56 feat: markdown previewer implemented
  sw.js
  tools/markdown-previewer/index.html
  tools/markdown-previewer/script.js
Labels: hacktoberfest-accepted

#58 feat: Add Password Generator
  index.html
  tools/password-generator/README.md
  tools/password-generator/index.html
  tools/password-generator/script.js
  tools/password-generator/style.css
  tools/unix-timestamp-converter/README.md
  tools/unix-timestamp-converter/index.html
  tools/unix-timestamp-converter/script.js
  tools/unix-timestamp-converter/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#46 Add "mise.toml" to simplify project setup
  mise.toml
Labels: hacktoberfest, hacktoberfest-accepted

#61 Modified CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest-accepted

#77 Update README.md
  README.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#78 Update README.md
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#79 Update README.md
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#81 Updated sw.js
  sw.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#83 Update AWESOME.md
  AWESOME.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#82 fix(pwa): correct service worker registration for GitHub Pages
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#65 Added code beautifier
  index.html
  tools/code-beautifier/index.html
  tools/code-beautifier/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#63 Added sidebar and fixed to navbar
  index.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#92 feat: Added Percentage Calculator tool
  index.html
  tools/percentage-calculator/index.html
  tools/percentage-calculator/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#91 Made Line Sorter/Unique Line Extractor
  index.html
  tools/line-sorter-unique/index.html
  tools/line-sorter-unique/script.js
  tools/line-sorter-unique/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#90 Added the Even Odd Checker Function
  index.html
  tools/even-odd-checker/index.html
  tools/even-odd-checker/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#121 bugfix-tools-counter: update tools counter
  index.html
  script.js
Labels: hacktoberfest, hacktoberfest-accepted

#119 fix_card_behaviour
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#103 bug-fix-active-filter-missing: Active Filter Button.
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#86 feat: Add Text Trimmer tool (Issue - #76)
  index.html
  tools/text-trimmer/index.html
  tools/text-trimmer/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#85 🔁 Text Repeater Tool
  index.html
  tools/text-repeater/index.html
  tools/text-repeater/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#101 Feat date tools
  index.html
  style.css
  tools/date-difference/index.html
  tools/date-difference/script.js
  tools/date-difference/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#114 Fix/search feature broken
  index.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#123 Add Back to Top button functionality
  index.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#227 Feat: Xml to JSON converter
  index.html
  script.js
  tools/xml-to-json-converter/index.html
  tools/xml-to-json-converter/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#232 Add Image Compressor/Optimizer Tool.
  index.html
  tools/image-compressor/index.html
  tools/image-compressor/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#230 feat json-yaml converter
  index.html
  tools/json-yaml-converter/index.html
  tools/json-yaml-converter/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#233 json-csv-converter
  index.html
  tools/json-csv-converter/index.html
  tools/json-csv-converter/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#235 css-specificity-calculator
  index.html
  tools/css-specificity-calculator/index.html
  tools/css-specificity-calculator/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#234 css-grid-generator
  index.html
  tools/css-grid-generator/index.html
  tools/css-grid-generator/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#283 Add json formatter
  index.html
  tools/json-formatter/index.html
  tools/json-formatter/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#284 simple tool for emi calculator
  index.html
  tools/emi-calculator/index.html
  tools/emi-calculator/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#285 Add the new component image cropper
  index.html
  tools/image-cropper/index.html
  tools/image-cropper/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#292 feat: Simple 'Internet Speed' Test Tool #270 and Solved UI Issue UI I…
  index.html
  tools/internet-speed/index.html
  tools/internet-speed/script.js
  tools/internet-speed/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#294 Add File Encryptor & Decryptor
  index.html
  tools/file-encryptor/index.html
  tools/file-encryptor/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#303 feat: Create a Responsive Aspect Ratio Calculator
  index.html
  tools/aspect-ratio-calculator/README.md
  tools/aspect-ratio-calculator/index.html
  tools/aspect-ratio-calculator/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#305 Csv viewer
  index.html
  tools/csv-viewer/index.html
  tools/csv-viewer/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#298 feat: Create a Browser Geolocation & Map Tool
  index.html
  tools/geolocation/README.md
  tools/geolocation/index.html
  tools/geolocation/leaflet/images/layers-2x.png
  tools/geolocation/leaflet/images/layers.png
  tools/geolocation/leaflet/images/marker-icon-2x.png
  tools/geolocation/leaflet/images/marker-icon.png
  tools/geolocation/leaflet/images/marker-shadow.png
  tools/geolocation/leaflet/leaflet-src.esm.js
  tools/geolocation/leaflet/leaflet-src.esm.js.map
  tools/geolocation/leaflet/leaflet-src.js
  tools/geolocation/leaflet/leaflet-src.js.map
  tools/geolocation/leaflet/leaflet.css
  tools/geolocation/leaflet/leaflet.js
  tools/geolocation/leaflet/leaflet.js.map
  tools/geolocation/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#307 issue 278 solved successfully
  index.html
  tools/exif-remover/index.html
  tools/exif-remover/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#313 Issue #124 [Tool]: Added OCR-based Text extraction tool
  index.html
  script.js
  tools/text-extractor/index.html
  tools/text-extractor/scripts.js
Labels: hacktoberfest, hacktoberfest-accepted

#314 simple Cookie Editor/Viewer
  cookie-manager/index.html
  cookie-manager/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#315 Add a Relative Time Formatter
  index.html
  tools/relative-date/index.html
  tools/relative-date/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#316 simple Color Palette Generator
  index.html
  tools/color-palette-generator/index.html
  tools/color-palette-generator/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#309 Create a simple CSS Animation Library/Previewer
  index.html
  tools/css-animations/index.html
  tools/css-animations/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#327 feat: Add Character Case Checker tool
  index.html
  tools/character-case-checker/index.html
  tools/character-case-checker/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#329 Text to Ascii Converter
  index.html
  tools/text-to-ascii-converter/index.html
  tools/text-to-ascii-converter/script.js
Labels: hacktoberfest, hacktoberfest-accepted
